"""
Rate-model calibration, Master-plan MC (calibration phase).

Calibrates the M3 rate models to a market of swaption / caplet volatilities,
each with a least-squares fit on relative price errors (mirroring
`calibrate_hull_white`). Engines used for calibration are the *analytic* ones
where available (G2++ closed-form swaption, LMM Black caplets / Rebonato
swaption vol, BK tree, HW for Cheyette's constant-vol limit) so the optimiser
sees a smooth, noise-free objective.

Each calibrator returns {params..., rmse, instruments(table), converged}. The
phase is validated identity-first: the LMM caplet strip recovers its per-rate
vols *exactly* (caplet = Black by construction); G2++/BK/LMM-swaption/Cheyette
round-trip — calibrating to a surface generated by the model itself reprices it
to within rmse tolerance.
"""

from __future__ import annotations

import numpy as np
from scipy.optimize import least_squares, brentq

from models.short_rate import (_forward_swap_rate, black_swaption_price,
                               calibrate_hull_white)
from models.g2pp import G2pp
from models.black_karasinski import BlackKarasinski
from models.cheyette import Cheyette


def _atm_market(curve, cube, instruments, freq, notional):
    """ATM forward strikes + Black market prices for a set of (T_opt, T_swap)."""
    strikes, market = [], []
    for T_opt, T_swap in instruments:
        S0, _ = _forward_swap_rate(curve, T_opt, T_swap, freq)
        vol = cube.atm_vol(T_opt, T_swap)
        strikes.append(S0)
        market.append(black_swaption_price(notional, S0, T_opt, T_swap, freq, curve, vol))
    return strikes, market


def _report(instruments, strikes, market, model_prices):
    table = []
    for (T_opt, T_swap), K, mkt, mdl in zip(instruments, strikes, market, model_prices):
        table.append(dict(T_opt=T_opt, T_swap=T_swap, strike=K, market=mkt,
                          model=mdl, rel_error=(mdl - mkt) / max(abs(mkt), 1e-12)))
    rmse = float(np.sqrt(np.mean([r["rel_error"] ** 2 for r in table])))
    return table, rmse


# ── G2++ (analytic swaption surface) ─────────────────────────

def calibrate_g2pp(curve, cube, instruments, freq=2, notional=1.0, n_x=64):
    """Calibrate G2++ (a, σ, b, η, ρ) to the ATM swaption surface."""
    strikes, market = _atm_market(curve, cube, instruments, freq, notional)

    def model_prices(p):
        a, s, b, e, rho = p
        g = G2pp(curve, a, s, b, e, rho)
        return [g.swaption_analytic(notional, K, T_opt, T_swap, freq, "payer", n_x)
                for (T_opt, T_swap), K in zip(instruments, strikes)]

    def resid(p):
        return [(m - mkt) / max(abs(mkt), 1e-12)
                for m, mkt in zip(model_prices(p), market)]

    x0 = [0.08, 0.008, 0.4, 0.010, -0.5]
    lo = [1e-3, 1e-4, 1e-3, 1e-4, -0.99]
    hi = [3.0, 0.1, 3.0, 0.1, 0.5]
    res = least_squares(resid, x0=x0, bounds=(lo, hi), xtol=1e-10, ftol=1e-10)
    a, s, b, e, rho = res.x
    table, rmse = _report(instruments, strikes, market, model_prices(res.x))
    return dict(a=float(a), sigma=float(s), b=float(b), eta=float(e), rho=float(rho),
                rmse=rmse, instruments=table, converged=bool(res.success))


# ── LMM caplet strip (exact per-rate vols) ───────────────────

def calibrate_lmm_caplets(curve, strip, end, freq=2):
    """Per-rate LMM vols from a caplet vol strip — exact, since each caplet is
    Black by construction. Returns the σ_k for forwards L_1..L_{N-1}."""
    from models.lmm import LMM
    m = LMM(curve, start=0.0, end=end, freq=freq)
    vols = np.array([strip.vol(m.reset[k]) for k in range(m.N)])
    return dict(vols=vols, resets=m.reset.copy(),
                model=LMM(curve, start=0.0, end=end, freq=freq, vols=vols))


# ── LMM swaption surface (flat vol + correlation β, Rebonato) ─

def calibrate_lmm_swaptions(curve, cube, instruments, freq=2, notional=1.0,
                            end=None):
    """Calibrate a flat LMM vol and correlation decay β to the ATM swaption
    surface via the analytic Rebonato vol."""
    from models.lmm import LMM
    end = end or max(T_opt + T_swap for T_opt, T_swap in instruments)
    strikes, market = _atm_market(curve, cube, instruments, freq, notional)

    def model_prices(p):
        vol, beta = p
        m = LMM(curve, start=0.0, end=end, freq=freq, vol=vol, corr_beta=beta)
        out = []
        for (T_opt, T_swap), K in zip(instruments, strikes):
            a = int(round(T_opt * freq))
            b = int(round((T_opt + T_swap) * freq))
            out.append(m.swaption_black(notional, K, a, b, "payer"))
        return out

    def resid(p):
        return [(m - mkt) / max(abs(mkt), 1e-12)
                for m, mkt in zip(model_prices(p), market)]

    res = least_squares(resid, x0=[0.20, 0.05], bounds=([1e-3, 0.0], [2.0, 2.0]),
                        xtol=1e-10, ftol=1e-10)
    vol, beta = res.x
    table, rmse = _report(instruments, strikes, market, model_prices(res.x))
    return dict(vol=float(vol), corr_beta=float(beta), rmse=rmse,
                instruments=table, converged=bool(res.success))


# ── Black-Karasinski (tree, ATM surface) ─────────────────────

def calibrate_bk(curve, cube, instruments, freq=2, notional=1.0, steps_per_year=16):
    """Calibrate Black-Karasinski (a, σ) to the ATM swaption surface (tree)."""
    strikes, market = _atm_market(curve, cube, instruments, freq, notional)
    max(T_opt + T_swap for T_opt, T_swap in instruments)

    def model_prices(p):
        a, s = p
        out = []
        for (T_opt, T_swap), K in zip(instruments, strikes):
            tree = BlackKarasinski(a, s, curve, T_opt + T_swap, steps_per_year)
            out.append(tree.swaption(notional, K, T_opt, T_swap, freq, "payer")["price"])
        return out

    def resid(p):
        return [(m - mkt) / max(abs(mkt), 1e-12)
                for m, mkt in zip(model_prices(p), market)]

    res = least_squares(resid, x0=[0.1, 0.20], bounds=([1e-3, 1e-3], [3.0, 2.0]),
                        xtol=1e-8, ftol=1e-8, diff_step=1e-3)
    a, s = res.x
    table, rmse = _report(instruments, strikes, market, model_prices(res.x))
    return dict(a=float(a), sigma=float(s), rmse=rmse, instruments=table,
                converged=bool(res.success))


# ── Cheyette (HW-equivalent ATM + smile skew) ────────────────

def calibrate_cheyette(curve, cube, instruments, freq=2, notional=1.0):
    """Calibrate Cheyette: the constant-vol part (a, σ) IS Hull-White, so reuse
    the HW calibration; the local-vol skew is left at 0 (ATM target) and is
    calibrated separately to the smile when smile quotes are supplied."""
    hw = calibrate_hull_white(curve, cube, instruments, freq, notional)
    return dict(a=hw["kappa"], sigma=hw["sigma"], skew=0.0, rmse=hw["rmse"],
                instruments=hw["instruments"], converged=hw["converged"])


def calibrate_cheyette_skew(curve, a, sigma, T_opt, T_swap, strikes, market_vols,
                            freq=2, n_sims=80_000, steps=80, seed=11):
    """Calibrate the Cheyette local-vol skew to a swaption smile (one expiry ×
    tenor), holding (a, σ) from the ATM/HW fit. Common random numbers (fixed
    seed) keep the MC objective smooth in the single skew parameter."""
    from models.black_scholes import black76
    S0, ann = _forward_swap_rate(curve, T_opt, T_swap, freq)

    def implied(price, K):
        try:
            return brentq(lambda v: ann * black76(S0, K, T_opt, 0, v, "call").price - price,
                          1e-4, 3.0)
        except ValueError:
            return np.nan

    def resid(p):
        ch = Cheyette(curve, a, sigma, skew=p[0])
        out = []
        for K, mv in zip(strikes, market_vols):
            px = ch.swaption(1.0, K, T_opt, T_swap, freq, "payer", n_sims, steps, seed)["price"]
            out.append(implied(px, K) - mv)
        return out

    res = least_squares(resid, x0=[0.0], bounds=([-10.0], [10.0]),
                        xtol=1e-6, ftol=1e-8, diff_step=0.05)
    rmse = float(np.sqrt(np.mean(np.square(resid(res.x)))))
    return dict(skew=float(res.x[0]), a=a, sigma=sigma, rmse=rmse,
                converged=bool(res.success))


def calibrate_lmm_instantaneous_vol(curve, strip, end, freq=2):
    """Bootstrap piecewise-constant LMM *instantaneous* forward vols v_j on each
    period from a caplet vol term structure: caplet_k variance = Σ_{j≤k} v_j²·τ.
    Closes the time-dependent-vol gap (the flat LMM uses one vol per forward).
    Returns v_j, the implied caplet vols (round-trip), and a no-arb flag."""
    from models.lmm import LMM
    m = LMM(curve, start=0.0, end=end, freq=freq)
    resets, tau = m.reset, m.tau
    cap_var = np.array([(strip.vol(resets[k]) ** 2) * resets[k] if resets[k] > 0 else 0.0
                        for k in range(m.N)])
    inst_var = np.empty(m.N)                            # v_j² per period
    prev = 0.0
    arb_free = True
    for k in range(m.N):
        inc = cap_var[k] - prev
        if inc < -1e-12:
            arb_free = False                            # total variance must rise
        inst_var[k] = max(inc, 0.0) / tau[k]
        prev = cap_var[k]
    inst_vol = np.sqrt(inst_var)
    # round-trip implied caplet vols from the bootstrapped instantaneous vols
    implied = np.array([np.sqrt(np.sum(inst_var[:k + 1] * tau[:k + 1]) / resets[k])
                        if resets[k] > 0 else 0.0 for k in range(m.N)])
    return dict(inst_vol=inst_vol, resets=resets.copy(), implied_caplet_vol=implied,
                arb_free=arb_free)


# ── unified dispatcher ───────────────────────────────────────

def calibrate_rate_model(model_id, curve, cube, instruments, freq=2, notional=1.0):
    """Dispatch to the per-model calibrator (swaption-surface targets)."""
    if model_id == "g2pp":
        return calibrate_g2pp(curve, cube, instruments, freq, notional)
    if model_id == "lmm":
        return calibrate_lmm_swaptions(curve, cube, instruments, freq, notional)
    if model_id == "bk":
        return calibrate_bk(curve, cube, instruments, freq, notional)
    if model_id == "cheyette":
        return calibrate_cheyette(curve, cube, instruments, freq, notional)
    if model_id in ("hw", "hull_white", "short_rate"):
        return calibrate_hull_white(curve, cube, instruments, freq, notional)
    raise ValueError(f"no rate calibrator for model_id={model_id!r}")
